version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  
jobs:
  # aegdevel
  # - Install
  # - Authenticate
  # - Deploy
  deploy-DuyHuynhDevOrg-job:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          instanceUrl: https://login.salesforce.com/
          defaultusername: duy.huynh@isobar.com
          consumerKey: CONSUMER_KEY
          jwtKey: JWT_KEY
      - run:
          name: Check Auth List
          command: sfdx force:auth:list
      - run:
          name: Deploy
          command: sfdx force:source:deploy -p force-app/main/default/classes/Main2.cls -u duy.huynh@isobar.com
          
  deploy-MichaelHuynhDevOrg-job:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          instanceUrl: https://login.salesforce.com/
          defaultusername: michael.huynh@circleci.com
          consumerKey: CONSUMER_KEY_DEV_ORG
          jwtKey: JWT_KEY_DEV_ORG
      - run:
          name: Check Auth List
          command: sfdx force:auth:list
      - run:
          name: Deploy
          command: sfdx force:source:deploy -p force-app/main/default/classes/Dev1Branch.cls -u michael.huynh@circleci.com
          
workflows:
    version: 2
    deploy-DuyHuynhDevOrg-workflow:
     jobs:
      - deploy-DuyHuynhDevOrg-job:
          filters:
            branches:
              only: main
              
    deploy-MichaelHuynhDevOrg-workflow:
     jobs:
      - deploy-MichaelHuynhDevOrg-job:
          filters:
            branches:
              only: feature/Dev1