version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  
jobs:
  # aegdevel
  # - Install
  # - Authenticate
  # - Deploy
  deploy-DuyHuynhDevOrg-job:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          instanceUrl: https://login.salesforce.com/
          defaultusername: duy.huynh@isobar.com
          defaultdevhubusername: duyhuynhDevOrg
          consumerKey: 3MVG97quAmFZJfVyrGIgm4n0Sb7LgnJjsNCN35CnDA_vX1CfOotPjj4J1RJOxQBtL2OgzVWtGE4sMUBhmwlLD
          jwtKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeVNteHlabzJr
TWxmaEJxSmdiaXdnKzIrRDZ6dm5WSDMrNHMrcHFSWlJURm1uUTJ2CkVRZDFTYmFYUWd0T21ZVVJT
SlRSVHBxRGQ5ZWJmUTFHOE5BMHdnSnM0ZmlGZHZteDA1eS9LVFV6dXg1SDFhYTUKbi9zVSswc3lZ
RzhCQlNySmViUHRDWjVZL3lhc0F2cjlNUUM1QXJ6clFPUmRtNVI1MGtCbjNrRmo3UDNNbk1qUQpE
SFdndzNTbytKMzMyNVRWajQ0bWJoc0lVYmhrTWd0NGUrUVNHU05LUDVkb3ZJSlhFa0RyeUxKUS91
Tm5MMUR2CjdTUXNuVzFaTWsvc282UVNQWXZtb0FoVU85di9EYUdHNy9wK3gwU0p6Mm9WckppTHVI
WHpjMjVzWGVhSEltK2oKa3VsTjNRcUJiWmxnQm5mVERiZG42eVVLYzVMRkxtYlB5ZEhtTlFJREFR
QUJBb0lCQUEwc2tkd21JVlN5RzNOSApXYUlKT21ZcGQ3MEhFbG8zT0FwZFFDa2hza2I1eVVLWDF0
TkNyY2U2RVlYZHY3UUdKdStkNzJjNmIwbTE4UlRyCmZhM2Z0TlRQMjltZ3NQenR0VnVxZEVwNmxY
eTNxdlN2Q3BFVG5IZ29vSS80TlJUbGpIUlArRUlkQUs4VkZVYk0Kc1RBNFgrVnlBZVlxRG9kVjNm
U0xDMEplL2ZCVFFOMWMxMmhCdnZDUmxsdjZjMUJkdEtuOGw0VHN1aUpiZFpyNwpWVTBjd0FqK3Yz
L0dGemNHaW9BaWJDLzUxZ2M2UUZmMkRJblRiakdPWnAyUy9xUE1MRkxNVWlFNm1hbDdYcDNkCmU4
NGF3OXdleUJtZmpLejBVMi9CWHA4T1l3YitLQVZHMFUwTHZJMkNvUmtKbENqb3Y2RkVpektrZXZM
S2VQWmYKZW04d0NvRUNnWUVBL2c2ZCtNWGxGSWxzdVozdVpra3lFMGxFSFNKc3J0U3VCZEMwdHJp
UXFZUzUraHlhWUhOUwp1VCtvNDNzOGV1MmltcW5ONHVtOUdXOGVhOWZmckhVVWRqRFlRQng1QSsx
c3Q1dlBKa0g0Nmdqb2ZabmdnVjgzCitYNDJaOStLWER5eEdzd1dWeStxcmNuYUY3cmM4UmZjekFK
WUkvSnNhV0hRaUViSFVwdnJqbGtDZ1lFQXlyT0YKN3hHSHhLSUZuUE1Yb2hyTGI0RWs5MCs0NTBM
NFBSSlAwakxjU1hXMDZoeHpxeXY1WGZZV2RtS1MwdWNCMXFZTwpIWHVtaVhXYityY213UmJGLzlh
K1ZOTnhGR3JEdTFLUHRwZ2tUQXJKaTFtVm5DVThTSUFhNW5QY1RkY3RYc1daCkZjS2R1WWR0a3NF
aFNGOHBxeEhOczYxWkdkWUhOQWJaNU0zWGN6MENnWUJMaGRqY0RTZ09OTlFIVWJWKzNwOXUKTUVk
NVNiUjVQR3dHK29YZUUzdWRpUUVvSXJ5WmsyNng5d1NqcXd6TmxqclNNMHdxK2tUbWZLdlVielhr
dEdGQwp5VDVmd0pjUTNkR0Z1MkdYQStHVTROVU1FV1ExMFRKNGpsWnFCbi9BNzZIT1Q0RU1wZlRj
K0xaR2U1d1daM3VSCmdkamx4cmtIa3JaRTdKVndMejJVOFFLQmdCZGpnNDdFVFJBcFNkQ0VWRFBH
TjdjVUJibnJud0JBUC9oOEJtM1EKcEk1dFlJU3E1OFhXZXgyV2FaMGJYcW1yTWhFY2RBQis1Z1p5
Wlo4V1J3aDhvamdWQlQwd2NKblVmK1U3YjQyNApIR2dSenBPZnNKMmx4a0R2Vnl0RUx5VmtNTDRB
dXR0QjY0VWUxVXZic1FWeXhaSVJxZFNUcWZaTE5lV1E3TTl6CjJPcFpBb0dCQU1nNERKNFk5a0U0
T1pnQ1Nrc3doTVlGb1hyWDZqemJzZEJjUEw4S1Nzem1MdXF4b3hCeTdFcm4KM2ZQMU9HZ3Z1dExt
QjlIVXErcVdrN2dPY1ZUL3JjbVkvU1dFUWRlazVhTmhxQVhJNW53dWUrdDZybWc4am1IMwp3QTkz
YXZtN1JKS1dvVkl1YTJKODdsQjgzQWhWcUdhTUcvcDN1ZEYvZUdzZU9FdXpqZGxzCi0tLS0tRU5E
IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
      - run:
          name: Check Auth List
          command: sfdx force:auth:list
      - run:
          name: Deploy
          command: sfdx force:source:deploy -p force-app/main/default/classes RunLocalTests
workflows:
    version: 2
    deploy-DuyHuynhDevOrg-workflow:
     jobs:
      - deploy-DuyHuynhDevOrg-job:
          filters:
            branches:
              only: main